spring:
  datasource:
    url: ${VANGUARD_DB_URL}
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis

  data:
    redis:
      url: ${VANGUARD_REDIS_URL}

  rabbitmq:
    uri: ${VANGUARD_RABBITMQ_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${VANGUARD_SMTP_USERNAME}
    password: ${VANGUARD_SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

vanguard:
  client:
    url: ${VANGUARD_CLIENT_URL}
  smtp:
    username: ${VANGUARD_SMTP_USERNAME}

auth:
  jwt:
    secret: ${VANGUARD_JWT_SECRET}
    expiration-ms: ${VANGUARD_JWT_EXPIRATION_MS}
    refresh-expiration-ms: ${VANGUARD_JWT_REFRESH_EXPIRATION_MS}
