spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    driver-class-name: org.postgresql.Driver
    username: dev
    password: dev

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

auth:
  jwt:
    secret: "vanguard_secret_dev_1234567890"
    expiration-ms: 900000
    refresh-expiration-ms: 604800000
