spring:
  datasource:
    url: ${VANGUARD_DB_URL}
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis

  data:
    redis:
      url: ${VANGUARD_REDIS_URL}

  rabbitmq:
    addresses: ${VANGUARD_RABBITMQ_URL}

auth:
  jwt:
    secret: ${VANGUARD_JWT_SECRET}
    expiration-ms: ${VANGUARD_JWT_EXPIRATION_MS}
    refresh-expiration-ms: ${VANGUARD_JWT_REFRESH_EXPIRATION_MS}
